// 1 . Using Tag

console.log(document.getElementsByTagName('header'));
console.log(document.getElementsByTagName('main'));
console.log(document.getElementsByTagName('footer'));
console.log(document.getElementsByTagName('li')[2]);

// 2 . Using Class Name

console.log(document.getElementsByClassName('container'));


// 3 . Using Id 

console.log(document.getElementById("home"));
console.log(document.getElementById("about"));
console.log(document.getElementById("contact"));

// 4 . Tag and Id

console.log(document.getElementsByTagName('style'));
console.log(document.getElementById("styles"));